num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))
soma = num1 + num2
print(f"A soma de {num1} + {num2} = {soma}")
subtracao = num1 - num2
print(f"A subtração de {num1} - {num2} = {subtracao}")
multiplicacao = num1 * num2
print(f"A multiplicação de {num1} * {num2} = {multiplicacao}")
divisao = num1 / num2
print(f"A divisão de {num1} / {num2} = {divisao}")